name: E2E Benchmark Regression Testing

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  deployments: write
  pull-requests: write

jobs:
  e2e-benchmark:
    if: github.event_name == 'pull_request' || (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'workflow_dispatch'
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
          - os: windows-latest
          - os: ubuntu-24.04-arm
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          filter: tree:0

      - uses: ./.github/actions/set-nx-shas

      - uses: ./.github/actions/setup-node-and-install

      # Download previous benchmark result from cache (if exists)
      - name: Resolve benchmark cache key
        id: benchmark-cache-key
        shell: bash
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            suffix="${{ github.event.pull_request.id }}"
          else
            branch="${{ github.ref_name }}"
            suffix="${branch//\//-}"
          fi
          echo "suffix=$suffix" >> "$GITHUB_OUTPUT"

      - name: Download previous benchmark data
        id: benchmark-cache-restore
        uses: actions/cache@v4
        with:
          path: ./benchmarks/workspace-e2e
          # Include run id to ensure each save uses a unique cache key
          key: ${{ format('{0}-e2e-benchmark-{1}-{2}', runner.os, steps.benchmark-cache-key.outputs.suffix, github.run_id) }}
          restore-keys: |
            ${{ format('{0}-e2e-benchmark-{1}-', runner.os, steps.benchmark-cache-key.outputs.suffix) }}
            ${{ format('{0}-e2e-benchmark-main-', runner.os) }}

      # Run E2E benchmark tests using Nx task
      - name: Run E2E benchmarks
        shell: bash
        run: |
          # Skip cache to ensure fresh benchmark results and capture all output
          npx nx benchmark workspace-e2e --skip-nx-cache 2>&1 | sed -E 's/^[[:space:]]*//' | tee workspace-e2e-benchmark.txt

      - name: Continuous Benchmark
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: E2E Move-File Generator Benchmarks (${{ matrix.os }})
          tool: 'benchmarkjs'
          output-file-path: workspace-e2e-benchmark.txt
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # Store benchmark data in external JSON file per OS
          external-data-json-path: ./benchmarks/workspace-e2e/${{ runner.os }}-benchmark.json
          # Disable GitHub Pages integration
          save-data-file: true
          skip-fetch-gh-pages: true
          alert-threshold: '120%'
          comment-on-alert: true
          fail-on-alert: true
          alert-comment-cc-users: '@LayZeeDK'
          summary-always: true

      - name: '[PR] Save benchmark cache'
        if: ${{ success() && steps.benchmark-cache-key.outputs.suffix != 'main' }}
        uses: actions/cache/save@v4
        with:
          path: ./benchmarks/workspace-e2e
          key: ${{ format('{0}-e2e-benchmark-{1}-{2}', runner.os, steps.benchmark-cache-key.outputs.suffix, github.run_id) }}

      - name: '[Merge] Save benchmark cache'
        if: ${{ success() && steps.benchmark-cache-key.outputs.suffix == 'main' && github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: actions/cache/save@v4
        with:
          path: ./benchmarks/workspace-e2e
          key: ${{ format('{0}-e2e-benchmark-main-{1}', runner.os, github.run_id) }}
