name: Claude Run (Reusable)
#
# Permission Documentation
# =======================
#
# This reusable workflow is called by multiple jobs in claude.yml
#
# Job: run
# Permissions:
#   - contents:write: Push commits to the repository
#   - pull-requests:write: Create/update PRs and PR comments
#   - issues:write: Create/update issue comments
#   - id-token:write: OIDC authentication with Claude Code service
#   - actions:read: Access workflow run information
#
# These permissions are required for Claude Code to:
# 1. Check out the repository
# 2. Make code changes and commit them
# 3. Push commits to the PR branch
# 4. Update PR descriptions and comments
# 5. Reply to issue/PR comments
# 6. Authenticate with the Claude Code service via OIDC
#

# Reusable workflow for running Claude Code with shared configuration
# Called by claude.yml with different trigger contexts

on:
  workflow_call:
    inputs:
      skip_branch_check:
        description: 'Skip the branch check (for issue-based triggers where Claude creates the branch)'
        required: false
        type: boolean
        default: false
      checkout_ref:
        description: 'Git ref to checkout (branch name, PR head ref, etc.)'
        required: false
        type: string
      issue_number:
        description: 'Issue or PR number for concurrency grouping'
        required: false
        type: string
      custom_prompt:
        description: 'Custom prompt for Claude'
        required: false
        type: string
    secrets:
      CLAUDE_CODE_OAUTH_TOKEN:
        required: true

jobs:
  # Main execution job for Claude Code
  # Permissions:
  #   - contents:write: Push commits to repository
  #   - pull-requests:write: Create/update PRs and PR comments
  #   - issues:write: Create/update issue comments
  #   - id-token:write: OIDC authentication with Claude Code service
  #   - actions:read: Access workflow run information
  run:
    runs-on: ubuntu-24.04-arm
    concurrency:
      group: claude-${{ inputs.issue_number || github.ref_name }}
      cancel-in-progress: false
    permissions:
      contents: write
      pull-requests: write
      issues: write
      id-token: write
      actions: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # We need to fetch all branches and commits so that Nx affected has a base to compare against.
          fetch-depth: 0
          filter: tree:0 # Optional, but recommended: reduce the size of the checkout with tree filtering, see https://github.blog/open-source/git/get-up-to-speed-with-partial-clone-and-shallow-clone/
          ref: ${{ inputs.checkout_ref || github.ref }}
          token: ${{ github.token }}

      - name: Prevent commits to main branch
        if: ${{ !inputs.skip_branch_check }}
        run: |
          # Get the actual checked-out branch name
          CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
          DEFAULT_BRANCH="${{ github.event.repository.default_branch }}"

          if [ "$CURRENT_BRANCH" = "$DEFAULT_BRANCH" ] || [ "$CURRENT_BRANCH" = "main" ] || [ "$CURRENT_BRANCH" = "master" ]; then
            echo "❌ Error: Claude cannot push commits to the main branch ($CURRENT_BRANCH)"
            exit 1
          fi

          echo "✅ Branch check passed: Working on non-main branch ($CURRENT_BRANCH)"

      - name: Install Git pre-push hook
        run: |
          DEFAULT_BRANCH="${{ github.event.repository.default_branch }}"

          cat > .git/hooks/pre-push << EOF
          #!/bin/sh
          DEFAULT_BRANCH="$DEFAULT_BRANCH"

          while read local_ref local_sha remote_ref remote_sha; do
            branch=\$(echo "\$remote_ref" | sed 's/refs\/heads\///')
            if [ "\$branch" = "main" ] || [ "\$branch" = "master" ] || [ "\$branch" = "\$DEFAULT_BRANCH" ]; then
              echo "❌ Error: pre-push hook blocked push to protected branch: \$branch"
              exit 1
            fi
          done
          exit 0
          EOF

          chmod +x .git/hooks/pre-push

      - name: Set Nx SHAs
        uses: ./.github/actions/set-nx-shas

      - name: Set up Node.js and install packages
        uses: ./.github/actions/setup-node-and-install

      - name: Sanitize custom prompt
        id: sanitize_prompt
        run: |
          # Sanitize the custom_prompt to prevent prompt injection attacks
          # Remove or escape any potential prompt injection patterns
          CUSTOM_PROMPT=$(cat <<'PROMPT_INPUT'
          ${{ inputs.custom_prompt }}
          PROMPT_INPUT
          )

          # Remove common prompt injection patterns while preserving legitimate content:
          # 1. Remove markdown code fences that might contain instructions
          # 2. Remove lines that look like system instructions (e.g., "You are...", "Your role is...")
          # 3. Remove lines with role-playing attempts (e.g., "Act as...", "Pretend to be...")
          # 4. Escape any attempt to override instructions

          SANITIZED_PROMPT=$(echo "$CUSTOM_PROMPT" | \
            # Remove markdown code fences with "system", "assistant", "user" markers
            sed '/^```[[:space:]]*\(system\|assistant\|user\)/,/^```/d' | \
            # Remove lines attempting to override the assistant's role
            sed '/^[[:space:]]*\(You are\|Your role\|Act as\|Pretend to be\|Ignore previous\|Disregard\|Override\)/Id' | \
            # Remove XML-style tags that might be used for prompt injection
            sed 's/<\(system\|assistant\|user\|instruction\|prompt\)>.*<\/\1>//gI' | \
            # Limit consecutive newlines to prevent spacing-based injection
            sed '/^$/N;/^\n$/D'
          )

          # Output the sanitized prompt
          {
            echo 'sanitized_prompt<<EOF'
            echo "$SANITIZED_PROMPT"
            echo 'EOF'
          } >> $GITHUB_OUTPUT

      - name: Build Claude prompt
        id: build_prompt
        run: |
          # Build combined prompt (system instructions + user prompt)
          # The Claude GitHub action doesn't support --system arg, so we combine them
          {
            echo 'CLAUDE_PROMPT<<EOF'
            echo 'You are an autonomous coding assistant running in a GitHub Actions workflow. Your role is to:'
            echo ''
            echo '1. **Work autonomously** - Complete the given task independently without asking for clarification'
            echo '2. **Push your commits** - Always push your commits using git push when you finish working on a task'
            echo '3. **Report via GitHub CLI** - Use gh pr comment to post updates and completion status to the PR'
            echo '4. **Handle errors gracefully** - If you encounter permission errors, report them via PR comments'
            echo ''
            echo '## Workflow Guidelines'
            echo ''
            echo '- Make focused, incremental commits with clear commit messages'
            echo '- After completing your work, push all commits: git push origin <branch-name>'
            echo '- Post a summary comment to the PR when done: gh pr comment <pr-number> --body "✅ Completed: <summary>"'
            echo '- Follow the repository conventions in AGENTS.md and other documentation'
            echo '- Run linters, formatters, and tests as appropriate for the changes'
            echo ''
            echo '## GitHub Actions Workflows Restriction'
            echo ''
            echo '⚠️ **IMPORTANT**: You do not have `workflows:write` permission and cannot directly modify files in `.github/workflows/` or `.github/actions/`.'
            echo ''
            echo 'If a task requires changes to GitHub Actions workflows or actions, you have two options:'
            echo ''
            echo '**Option 1: Provide a Git patch file**'
            echo ''
            echo '1. Create the modified workflow/action files in a non-ignored directory (e.g., `workflow-patches/`)'
            echo '2. Generate a Git patch that shows the changes needed:'
            echo '   - Use `git diff --no-index .github/workflows/original.yml workflow-patches/modified.yml > workflow-changes.patch`'
            echo '   - Or create a patch manually showing the exact changes'
            echo '3. Commit the patch file to the repository'
            echo '4. Push your commits'
            echo '5. Post a PR comment with instructions for applying the patch, such as:'
            echo '   ```'
            echo '   ## GitHub Actions Changes Required'
            echo '   '
            echo '   I have prepared the necessary workflow changes but cannot directly modify `.github/workflows/` due to permission restrictions.'
            echo '   '
            echo '   **Please apply the patch file with these commands:**'
            echo '   ```bash'
            echo '   git apply workflow-changes.patch'
            echo '   git add .github/workflows/'
            echo '   git commit -m "chore: apply workflow changes"'
            echo '   git push'
            echo '   ```'
            echo '   '
            echo '   Alternatively, review the patch file and apply the changes manually.'
            echo '   ```'
            echo ''
            echo '**Option 2: Provide detailed manual instructions**'
            echo ''
            echo '1. Analyze what changes are needed to the workflow/action files'
            echo '2. Post a detailed PR comment with step-by-step instructions for the user to make the changes manually, including:'
            echo '   - Exact file paths to modify'
            echo '   - Specific lines to change (with before/after examples)'
            echo '   - Complete diff or code blocks showing the changes'
            echo '   - Explanation of why each change is needed'
            echo ''
            echo '**Choose the option that makes the most sense based on the scope of changes:**'
            echo '- Use Option 1 (patch file) for new workflows or major restructuring'
            echo '- Use Option 2 (manual instructions) for small, targeted edits to existing workflows'
            echo ''
            echo '## Permission Denied Handling'
            echo ''
            echo 'If you encounter a permission denied or tool not allowed error, post a comment with:'
            echo ''
            echo 'Markdown code block with:'
            echo '## Permission Denied'
            echo ''
            echo '**Command:** <command>'
            echo '**Intent:** <what you were trying to accomplish>'
            echo '**Task:** <the specific task you were working on>'
            echo '**Context:** <additional context>'
            echo ''
            echo '---'
            echo ''
            echo '## Task'
            echo ''
            cat <<'PROMPT_END'
          ${{ steps.sanitize_prompt.outputs.sanitized_prompt }}
          PROMPT_END
            echo 'EOF'
          } >> $GITHUB_OUTPUT

      - name: Run Claude Code
        uses: anthropics/claude-code-action@v1
        with:
          github_token: ${{ github.token }}
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          additional_permissions: |
            actions: read
          prompt: ${{ steps.build_prompt.outputs.CLAUDE_PROMPT }}
          claude_args: |
            --allowed-tools '
              Read,
              Grep,
              Edit,
              MultiEdit,
              Write,
              LS,
              mcp:nx:*,
              WebSearch,
              WebFetch(domain:github.com),
              WebFetch(domain:nx.dev),
              Bash(git log:*),
              Bash(git status),
              Bash(git diff:*),
              Bash(git add:*),
              Bash(git commit:*),
              Bash(git push:*),
              Bash(git reset:*),
              Bash(git checkout:*),
              Bash(git branch:*),
              Bash(git show:*),
              Bash(git remote:*),
              Bash(git fetch:*),
              Bash(git tag:*),
              Bash(git stash:*),
              Bash(git config --get:*),
              Bash(git config --list),
              Bash(pwd),
              Bash(find:*),
              Bash(cat:*),
              Bash(head:*),
              Bash(tail:*),
              Bash(wc:*),
              Bash(sort:*),
              Bash(uniq:*),
              Bash(tree:*),
              Bash(which:*),
              Bash(mkdir:*),
              Bash(mv:*),
              Bash(cp:*),
              Bash(touch:*),
              Bash(sed:*),
              Bash(awk:*),
              Bash(cut:*),
              Bash(node:*),
              Bash(python:*),
              Bash(python3:*),
              Bash(npm install),
              Bash(npm run:*),
              Bash(npx nx:*),
              Bash(gh auth status),
              Bash(gh help),
              Bash(gh version),
              Bash(gh status),
              Bash(gh repo list nx-worker --limit 100),
              Bash(gh repo view nx-worker/nxworker-workspace --json name,description,visibility,defaultBranchRef,archived,isTemplate),
              Bash(gh issue list --repo nx-worker/nxworker-workspace --state all --limit 100),
              Bash(gh issue view:*),
              Bash(gh issue status --repo nx-worker/nxworker-workspace),
              Bash(gh issue comment:*),
              Bash(gh issue edit:*),
              Bash(gh issue close:*),
              Bash(gh pr list --repo nx-worker/nxworker-workspace --state all --limit 100),
              Bash(gh pr view --repo nx-worker/nxworker-workspace --json number,title,state,author,baseRefName,headRefName,mergeable:*),
              Bash(gh pr diff --repo nx-worker/nxworker-workspace:*),
              Bash(gh pr checks --repo nx-worker/nxworker-workspace:*),
              Bash(gh pr comment:*),
              Bash(gh pr edit:*),
              Bash(gh pr ready:*),
              Bash(gh release list --repo nx-worker/nxworker-workspace --limit 50),
              Bash(gh release view --repo nx-worker/nxworker-workspace --json tagName,name,publishedAt,url:*),
              Bash(gh workflow list --repo nx-worker/nxworker-workspace --limit 50),
              Bash(gh workflow view --repo nx-worker/nxworker-workspace --json name,path,state,createdAt,updatedAt:*),
              Bash(gh run list --repo nx-worker/nxworker-workspace --limit 50),
              Bash(gh run view --repo nx-worker/nxworker-workspace --json databaseId,displayTitle,status,conclusion,workflowName,createdAt,updatedAt:*),
              Bash(gh run rerun:*),
              Bash(gh workflow run:*),
              Bash(gh search repos --limit 50 --json name,owner,description,stargazersCount:*),
              Bash(gh search issues --limit 50 --json number,title,state,repository,author:*),
              Bash(gh search prs --limit 50 --json number,title,state,repository,author:*),
              Bash(gh search code --limit 50:*),
              Bash(gh api --method GET /repos/nx-worker/nxworker-workspace),
              Bash(gh api --method GET /repos/nx-worker/nxworker-workspace/issues/:*),
              Bash(gh api --method GET /repos/nx-worker/nxworker-workspace/pulls/:*),
              Bash(gh extension list),
              Bash(gh alias list)
            '
            --mcp-config '{
              "mcpServers": {
                "nx": {
                  "type": "stdio",
                  "command": "npx",
                  "args": ["-y", "nx-mcp@latest"]
                }
              }
            }'
