name: Claude Code Review

on:
  pull_request:
    types: [labeled]

jobs:
  claude-review:
    # Security: Only trigger when 'claude-review' label is added by a trusted user
    #
    # Checks:
    #   1. Label added is 'claude-review' specifically
    #   2. Sender is a User (not a bot)
    #   3. PR author is trusted (MEMBER, OWNER, or COLLABORATOR)
    if: |
      github.event.label.name == 'claude-review' &&
      github.event.sender.type == 'User' &&
      (github.event.pull_request.author_association == 'MEMBER' ||
       github.event.pull_request.author_association == 'OWNER' ||
       github.event.pull_request.author_association == 'COLLABORATOR')
    concurrency:
      # Only one code review per PR at a time
      # Re-adding the label cancels in-progress reviews to provide fresh feedback
      group: claude-review-${{ github.event.pull_request.number }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write # Required for Claude to create PR reviews and comments
      issues: write # Required for PR comments (GitHub treats PR comments as issue comments in the API)
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Claude Code Review
        id: claude-review
        uses: anthropics/claude-code-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          prompt: |
            REPO: ${{ github.repository }}
            PR NUMBER: ${{ github.event.pull_request.number }}

            Please review this pull request and provide feedback on:
            - Code quality and best practices
            - Potential bugs or issues
            - Performance considerations
            - Security concerns
            - Test coverage

            Use the repository's AGENTS.md for guidance on style and conventions. Be constructive and helpful in your feedback.

            Use `gh pr comment` with your Bash tool to leave your review as a comment on the PR.

          # See https://github.com/anthropics/claude-code-action/blob/main/docs/usage.md
          # or https://docs.claude.com/en/docs/claude-code/cli-reference for available options
          claude_args: |
            --allowed-tools "Bash(gh issue view:*),Bash(gh search:*),Bash(gh issue list:*),Bash(gh pr comment:*),Bash(gh pr diff:*),Bash(gh pr view:*),Bash(gh pr list:*)"
            --mcp-config '{ "mcpServers": { "github": { "type": "http", "url": "https://api.githubcopilot.com/mcp/" }, "nx": { "type": "stdio", "command": "npx", "args": ["-y", "nx-mcp@latest"] } } }'
